// AUTO-GENERATED by tools/gen_tables.py -- do not edit by hand.
// Sources: awbw.amarriner.com units.php / terrain.php / js/damage_inc.json,
// plus the AWBW terrain-id table via RizeBot's generated terrain-table.ts.
#![cfg_attr(rustfmt, rustfmt_skip)]

use crate::types::{MoveType, TerrainKind, UnitType};

pub const NUM_UNIT_TYPES: usize = 25;
pub const NUM_TERRAIN_KINDS: usize = 22;

#[derive(Debug, Clone, Copy)]
pub struct UnitStats {
    pub name: &'static str,
    pub awbw_id: u32,
    pub cost: u32,
    pub move_points: u8,
    pub move_type: MoveType,
    pub max_ammo: u8,
    pub max_fuel: u8,
    pub fuel_per_turn: u8,
    pub fuel_per_turn_hidden: u8,
    pub vision: u8,
    pub range_min: u8,
    pub range_max: u8,
}

/// Indexed by `UnitType as usize`.
pub static UNIT_STATS: [UnitStats; 25] = [
    UnitStats { name: "Infantry", awbw_id: 1, cost: 1000, move_points: 3, move_type: MoveType::Foot, max_ammo: 0, max_fuel: 99, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "Mech", awbw_id: 2, cost: 3000, move_points: 2, move_type: MoveType::Boot, max_ammo: 3, max_fuel: 70, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "Md.Tank", awbw_id: 3, cost: 16000, move_points: 5, move_type: MoveType::Tread, max_ammo: 8, max_fuel: 50, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Tank", awbw_id: 4, cost: 7000, move_points: 6, move_type: MoveType::Tread, max_ammo: 9, max_fuel: 70, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 3, range_min: 0, range_max: 0 },
    UnitStats { name: "Recon", awbw_id: 5, cost: 4000, move_points: 8, move_type: MoveType::Tires, max_ammo: 0, max_fuel: 80, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 5, range_min: 0, range_max: 0 },
    UnitStats { name: "APC", awbw_id: 6, cost: 5000, move_points: 6, move_type: MoveType::Tread, max_ammo: 0, max_fuel: 70, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Artillery", awbw_id: 7, cost: 6000, move_points: 5, move_type: MoveType::Tread, max_ammo: 9, max_fuel: 50, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 2, range_max: 3 },
    UnitStats { name: "Rocket", awbw_id: 8, cost: 15000, move_points: 5, move_type: MoveType::Tires, max_ammo: 6, max_fuel: 50, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 3, range_max: 5 },
    UnitStats { name: "Anti-Air", awbw_id: 9, cost: 8000, move_points: 6, move_type: MoveType::Tread, max_ammo: 9, max_fuel: 60, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "Missile", awbw_id: 10, cost: 12000, move_points: 4, move_type: MoveType::Tires, max_ammo: 6, max_fuel: 50, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 5, range_min: 3, range_max: 5 },
    UnitStats { name: "Fighter", awbw_id: 11, cost: 20000, move_points: 9, move_type: MoveType::Air, max_ammo: 9, max_fuel: 99, fuel_per_turn: 5, fuel_per_turn_hidden: 5, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "Bomber", awbw_id: 12, cost: 22000, move_points: 7, move_type: MoveType::Air, max_ammo: 9, max_fuel: 99, fuel_per_turn: 5, fuel_per_turn_hidden: 5, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "B-Copter", awbw_id: 13, cost: 9000, move_points: 6, move_type: MoveType::Air, max_ammo: 6, max_fuel: 99, fuel_per_turn: 2, fuel_per_turn_hidden: 2, vision: 3, range_min: 0, range_max: 0 },
    UnitStats { name: "T-Copter", awbw_id: 14, cost: 5000, move_points: 6, move_type: MoveType::Air, max_ammo: 0, max_fuel: 99, fuel_per_turn: 2, fuel_per_turn_hidden: 2, vision: 2, range_min: 0, range_max: 0 },
    UnitStats { name: "Battleship", awbw_id: 15, cost: 28000, move_points: 5, move_type: MoveType::Sea, max_ammo: 9, max_fuel: 99, fuel_per_turn: 1, fuel_per_turn_hidden: 1, vision: 2, range_min: 2, range_max: 6 },
    UnitStats { name: "Cruiser", awbw_id: 16, cost: 18000, move_points: 6, move_type: MoveType::Sea, max_ammo: 9, max_fuel: 99, fuel_per_turn: 1, fuel_per_turn_hidden: 1, vision: 3, range_min: 0, range_max: 0 },
    UnitStats { name: "Lander", awbw_id: 17, cost: 12000, move_points: 6, move_type: MoveType::Lander, max_ammo: 0, max_fuel: 99, fuel_per_turn: 1, fuel_per_turn_hidden: 1, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Sub", awbw_id: 18, cost: 20000, move_points: 5, move_type: MoveType::Sea, max_ammo: 6, max_fuel: 60, fuel_per_turn: 1, fuel_per_turn_hidden: 5, vision: 5, range_min: 0, range_max: 0 },
    UnitStats { name: "Black Boat", awbw_id: 28, cost: 7500, move_points: 7, move_type: MoveType::Lander, max_ammo: 0, max_fuel: 60, fuel_per_turn: 1, fuel_per_turn_hidden: 1, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Carrier", awbw_id: 29, cost: 30000, move_points: 5, move_type: MoveType::Sea, max_ammo: 9, max_fuel: 99, fuel_per_turn: 1, fuel_per_turn_hidden: 1, vision: 4, range_min: 3, range_max: 8 },
    UnitStats { name: "Stealth", awbw_id: 30, cost: 24000, move_points: 6, move_type: MoveType::Air, max_ammo: 6, max_fuel: 60, fuel_per_turn: 5, fuel_per_turn_hidden: 8, vision: 4, range_min: 0, range_max: 0 },
    UnitStats { name: "Neotank", awbw_id: 46, cost: 22000, move_points: 6, move_type: MoveType::Tread, max_ammo: 9, max_fuel: 99, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Piperunner", awbw_id: 960900, cost: 20000, move_points: 9, move_type: MoveType::Pipe, max_ammo: 9, max_fuel: 99, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 4, range_min: 2, range_max: 5 },
    UnitStats { name: "Black Bomb", awbw_id: 968731, cost: 25000, move_points: 9, move_type: MoveType::Air, max_ammo: 0, max_fuel: 45, fuel_per_turn: 5, fuel_per_turn_hidden: 5, vision: 1, range_min: 0, range_max: 0 },
    UnitStats { name: "Mega Tank", awbw_id: 1141438, cost: 28000, move_points: 4, move_type: MoveType::Tread, max_ammo: 3, max_fuel: 50, fuel_per_turn: 0, fuel_per_turn_hidden: 0, vision: 1, range_min: 0, range_max: 0 },
];

/// Base damage % with the primary weapon;
/// -1 = this pairing cannot be attacked with this weapon.
/// Indexed [attacker as usize][defender as usize].
pub static BASE_DAMAGE_PRIMARY: [[i16; 25]; 25] = [
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Infantry
    [-1, -1, 15, 55, 85, 75, 70, 85, 65, 85, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 15, 55, -1, 5], // Mech
    [-1, -1, 55, 85, 105, 105, 105, 105, 105, 105, -1, -1, -1, -1, 10, 45, 35, 10, 35, 10, -1, 45, 85, -1, 25], // Md.Tank
    [-1, -1, 15, 55, 85, 75, 70, 85, 65, 85, -1, -1, -1, -1, 1, 5, 10, 1, 10, 1, -1, 15, 55, -1, 10], // Tank
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Recon
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // APC
    [90, 85, 45, 70, 80, 70, 75, 80, 75, 80, -1, -1, -1, -1, 40, 65, 55, 60, 55, 45, -1, 40, 70, -1, 15], // Artillery
    [95, 90, 55, 80, 90, 80, 80, 85, 85, 90, -1, -1, -1, -1, 55, 85, 60, 85, 60, 60, -1, 50, 80, -1, 25], // Rocket
    [105, 105, 10, 25, 60, 50, 50, 55, 45, 55, 65, 75, 120, 120, -1, -1, -1, -1, -1, -1, 75, 5, 25, 120, 1], // Anti-Air
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 100, 100, 120, 120, -1, -1, -1, -1, -1, -1, 100, -1, -1, 120, -1], // Missile
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 55, 100, 100, 100, -1, -1, -1, -1, -1, -1, 85, -1, -1, 120, -1], // Fighter
    [110, 110, 95, 105, 105, 105, 105, 105, 95, 105, -1, -1, -1, -1, 75, 85, 95, 95, 95, 75, -1, 90, 105, -1, 35], // Bomber
    [-1, -1, 25, 55, 55, 60, 65, 65, 25, 65, -1, -1, -1, -1, 25, 55, 25, 25, 25, 25, -1, 20, 55, -1, 10], // B-Copter
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // T-Copter
    [95, 90, 55, 80, 90, 80, 80, 85, 85, 90, -1, -1, -1, -1, 50, 95, 95, 95, 95, 60, -1, 50, 80, -1, 25], // Battleship
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 90, -1, -1, 100, -1, -1, -1, -1], // Cruiser
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Lander
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 55, 25, 95, 55, 95, 75, -1, -1, -1, -1, -1], // Sub
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Black Boat
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 100, 100, 115, 115, -1, -1, -1, -1, -1, -1, 100, -1, -1, 120, -1], // Carrier
    [90, 90, 70, 75, 85, 85, 75, 85, 50, 85, 45, 70, 85, 95, 45, 35, 65, 55, 65, 45, 55, 60, 80, 120, 15], // Stealth
    [-1, -1, 75, 105, 125, 125, 115, 125, 115, 125, -1, -1, -1, -1, 15, 50, 40, 15, 40, 15, -1, 55, 105, -1, 35], // Neotank
    [95, 90, 55, 80, 90, 80, 80, 85, 85, 90, 65, 75, 105, 105, 55, 60, 60, 85, 60, 60, 75, 50, 80, 120, 25], // Piperunner
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Black Bomb
    [-1, -1, 125, 180, 195, 195, 195, 195, 195, 195, -1, -1, -1, -1, 45, 65, 75, 45, 105, 45, -1, 115, 180, -1, 65], // Mega Tank
];

/// Base damage % with the secondary weapon;
/// -1 = this pairing cannot be attacked with this weapon.
/// Indexed [attacker as usize][defender as usize].
pub static BASE_DAMAGE_SECONDARY: [[i16; 25]; 25] = [
    [55, 45, 1, 5, 12, 14, 15, 25, 5, 25, -1, -1, 7, 30, -1, -1, -1, -1, -1, -1, -1, 1, 5, -1, 1], // Infantry
    [65, 55, 1, 6, 18, 20, 32, 35, 6, 35, -1, -1, 9, 35, -1, -1, -1, -1, -1, -1, -1, 1, 6, -1, 1], // Mech
    [105, 95, -1, 8, 45, 45, 45, 55, 7, 35, -1, -1, 12, 45, -1, -1, -1, -1, -1, -1, -1, 1, 8, -1, 1], // Md.Tank
    [75, 70, 1, 6, 40, 45, 45, 55, 5, 30, -1, -1, 10, 40, -1, -1, -1, -1, -1, -1, -1, 1, 6, -1, 1], // Tank
    [70, 65, 1, 6, 35, 45, 45, 55, 4, 28, -1, -1, 10, 35, -1, -1, -1, -1, -1, -1, -1, 1, 6, -1, 1], // Recon
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // APC
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Artillery
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Rocket
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Anti-Air
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Missile
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Fighter
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Bomber
    [75, 75, 1, 6, 30, 20, 25, 35, 6, 35, -1, -1, 65, 95, -1, -1, -1, -1, -1, -1, -1, 1, 6, -1, 1], // B-Copter
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // T-Copter
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Battleship
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 55, 65, 115, 115, -1, -1, -1, -1, 25, 5, -1, -1, -1, 120, -1], // Cruiser
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Lander
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Sub
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Black Boat
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Carrier
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Stealth
    [125, 115, 1, 10, 65, 65, 65, 75, 17, 55, -1, -1, 22, 55, -1, -1, -1, -1, -1, -1, -1, 1, 10, -1, 1], // Neotank
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Piperunner
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], // Black Bomb
    [135, 125, 1, 10, 65, 65, 65, 75, 17, 55, -1, -1, 22, 55, -1, -1, -1, -1, -1, -1, -1, 1, 10, -1, 1], // Mega Tank
];

/// Movement cost; 0 = impassable.
/// Indexed [TerrainKind as usize][Weather as usize][MoveType as usize].
pub static MOVE_COST: [[[u8; 8]; 3]; 22] = [
    [[1, 1, 1, 2, 1, 0, 0, 0], [1, 1, 2, 3, 1, 0, 0, 0], [2, 1, 2, 3, 2, 0, 0, 0]], // Plain
    [[2, 1, 0, 0, 1, 0, 0, 0], [2, 1, 0, 0, 1, 0, 0, 0], [4, 2, 0, 0, 2, 0, 0, 0]], // Mountain
    [[1, 1, 2, 3, 1, 0, 0, 0], [1, 1, 3, 4, 1, 0, 0, 0], [2, 1, 2, 3, 2, 0, 0, 0]], // Wood
    [[2, 1, 0, 0, 1, 0, 0, 0], [2, 1, 0, 0, 1, 0, 0, 0], [2, 1, 0, 0, 2, 0, 0, 0]], // River
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Road
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Bridge
    [[0, 0, 0, 0, 1, 1, 1, 0], [0, 0, 0, 0, 1, 1, 1, 0], [0, 0, 0, 0, 2, 2, 2, 0]], // Sea
    [[1, 1, 1, 1, 1, 0, 1, 0], [1, 1, 1, 1, 1, 0, 1, 0], [1, 1, 1, 1, 2, 0, 1, 0]], // Shoal
    [[0, 0, 0, 0, 1, 2, 2, 0], [0, 0, 0, 0, 1, 2, 2, 0], [0, 0, 0, 0, 2, 2, 2, 0]], // Reef
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // City
    [[1, 1, 1, 1, 1, 0, 0, 1], [1, 1, 1, 1, 1, 0, 0, 1], [1, 1, 1, 1, 2, 0, 0, 1]], // Base
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Airport
    [[1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 2, 2, 2, 0]], // Port
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Hq
    [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1]], // Pipe
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Silo
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // SiloEmpty
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // ComTower
    [[1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 2, 0, 0, 0]], // Lab
    [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], // Teleporter
    [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1]], // PipeSeam
    [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1]], // PipeRubble
];

/// Terrain defence stars, indexed by `TerrainKind as usize`.
/// Seams/rubble are stored as 0; AWBW also special-cases them to 0 in combat.
pub static TERRAIN_DEFENSE: [u8; 22] = [1, 4, 2, 0, 0, 0, 0, 0, 1, 3, 3, 3, 3, 4, 0, 3, 3, 3, 3, 0, 0, 0];

#[derive(Debug, Clone, Copy)]
pub struct TerrainIdInfo {
    pub kind: TerrainKind,
    /// Owning country code for pre-owned properties; None for neutral/none.
    pub country: Option<&'static str>,
}

/// AWBW `terrain_id` (as appearing in maps and replays) -> terrain info.
pub fn terrain_by_awbw_id(id: u16) -> Option<TerrainIdInfo> {
    let (kind, country) = match id {
        1 => (TerrainKind::Plain, None), // Plain
        2 => (TerrainKind::Mountain, None), // Mountain
        3 => (TerrainKind::Wood, None), // Wood
        4 => (TerrainKind::River, None), // HRiver
        5 => (TerrainKind::River, None), // VRiver
        6 => (TerrainKind::River, None), // CRiver
        7 => (TerrainKind::River, None), // ESRiver
        8 => (TerrainKind::River, None), // SWRiver
        9 => (TerrainKind::River, None), // WNRiver
        10 => (TerrainKind::River, None), // NERiver
        11 => (TerrainKind::River, None), // ESWRiver
        12 => (TerrainKind::River, None), // SWNRiver
        13 => (TerrainKind::River, None), // WNERiver
        14 => (TerrainKind::River, None), // NESRiver
        15 => (TerrainKind::Road, None), // HRoad
        16 => (TerrainKind::Road, None), // VRoad
        17 => (TerrainKind::Road, None), // CRoad
        18 => (TerrainKind::Road, None), // ESRoad
        19 => (TerrainKind::Road, None), // SWRoad
        20 => (TerrainKind::Road, None), // WNRoad
        21 => (TerrainKind::Road, None), // NERoad
        22 => (TerrainKind::Road, None), // ESWRoad
        23 => (TerrainKind::Road, None), // SWNRoad
        24 => (TerrainKind::Road, None), // WNERoad
        25 => (TerrainKind::Road, None), // NESRoad
        26 => (TerrainKind::Bridge, None), // HBridge
        27 => (TerrainKind::Bridge, None), // VBridge
        28 => (TerrainKind::Sea, None), // Sea
        29 => (TerrainKind::Shoal, None), // HShoal
        30 => (TerrainKind::Shoal, None), // HShoalN
        31 => (TerrainKind::Shoal, None), // VShoal
        32 => (TerrainKind::Shoal, None), // VShoalE
        33 => (TerrainKind::Reef, None), // Reef
        34 => (TerrainKind::City, None), // Neutral City
        35 => (TerrainKind::Base, None), // Neutral Base
        36 => (TerrainKind::Airport, None), // Neutral Airport
        37 => (TerrainKind::Port, None), // Neutral Port
        38 => (TerrainKind::City, Some("os")), // Orange Star City
        39 => (TerrainKind::Base, Some("os")), // Orange Star Base
        40 => (TerrainKind::Airport, Some("os")), // Orange Star Airport
        41 => (TerrainKind::Port, Some("os")), // Orange Star Port
        42 => (TerrainKind::Hq, Some("os")), // Orange Star HQ
        43 => (TerrainKind::City, Some("bm")), // Blue Moon City
        44 => (TerrainKind::Base, Some("bm")), // Blue Moon Base
        45 => (TerrainKind::Airport, Some("bm")), // Blue Moon Airport
        46 => (TerrainKind::Port, Some("bm")), // Blue Moon Port
        47 => (TerrainKind::Hq, Some("bm")), // Blue Moon HQ
        48 => (TerrainKind::City, Some("ge")), // Green Earth City
        49 => (TerrainKind::Base, Some("ge")), // Green Earth Base
        50 => (TerrainKind::Airport, Some("ge")), // Green Earth Airport
        51 => (TerrainKind::Port, Some("ge")), // Green Earth Port
        52 => (TerrainKind::Hq, Some("ge")), // Green Earth HQ
        53 => (TerrainKind::City, Some("yc")), // Yellow Comet City
        54 => (TerrainKind::Base, Some("yc")), // Yellow Comet Base
        55 => (TerrainKind::Airport, Some("yc")), // Yellow Comet Airport
        56 => (TerrainKind::Port, Some("yc")), // Yellow Comet Port
        57 => (TerrainKind::Hq, Some("yc")), // Yellow Comet HQ
        81 => (TerrainKind::City, Some("rf")), // Red Fire City
        82 => (TerrainKind::Base, Some("rf")), // Red Fire Base
        83 => (TerrainKind::Airport, Some("rf")), // Red Fire Airport
        84 => (TerrainKind::Port, Some("rf")), // Red Fire Port
        85 => (TerrainKind::Hq, Some("rf")), // Red Fire HQ
        86 => (TerrainKind::City, Some("gs")), // Grey Sky City
        87 => (TerrainKind::Base, Some("gs")), // Grey Sky Base
        88 => (TerrainKind::Airport, Some("gs")), // Grey Sky Airport
        89 => (TerrainKind::Port, Some("gs")), // Grey Sky Port
        90 => (TerrainKind::Hq, Some("gs")), // Grey Sky HQ
        91 => (TerrainKind::City, Some("bh")), // Black Hole City
        92 => (TerrainKind::Base, Some("bh")), // Black Hole Base
        93 => (TerrainKind::Airport, Some("bh")), // Black Hole Airport
        94 => (TerrainKind::Port, Some("bh")), // Black Hole Port
        95 => (TerrainKind::Hq, Some("bh")), // Black Hole HQ
        96 => (TerrainKind::City, Some("bd")), // Brown Desert City
        97 => (TerrainKind::Base, Some("bd")), // Brown Desert Base
        98 => (TerrainKind::Airport, Some("bd")), // Brown Desert Airport
        99 => (TerrainKind::Port, Some("bd")), // Brown Desert Port
        100 => (TerrainKind::Hq, Some("bd")), // Brown Desert HQ
        101 => (TerrainKind::Pipe, None), // VPipe
        102 => (TerrainKind::Pipe, None), // HPipe
        103 => (TerrainKind::Pipe, None), // NEPipe
        104 => (TerrainKind::Pipe, None), // ESPipe
        105 => (TerrainKind::Pipe, None), // SWPipe
        106 => (TerrainKind::Pipe, None), // WNPipe
        107 => (TerrainKind::Pipe, None), // NPipe End
        108 => (TerrainKind::Pipe, None), // EPipe End
        109 => (TerrainKind::Pipe, None), // SPipe End
        110 => (TerrainKind::Pipe, None), // WPipe End
        111 => (TerrainKind::Silo, None), // Missile Silo
        112 => (TerrainKind::SiloEmpty, None), // Missile Silo Empty
        113 => (TerrainKind::PipeSeam, None), // HPipe Seam
        114 => (TerrainKind::PipeSeam, None), // VPipe Seam
        115 => (TerrainKind::PipeRubble, None), // HPipe Rubble
        116 => (TerrainKind::PipeRubble, None), // VPipe Rubble
        117 => (TerrainKind::Airport, Some("ab")), // Amber Blossom Airport
        118 => (TerrainKind::Base, Some("ab")), // Amber Blossom Base
        119 => (TerrainKind::City, Some("ab")), // Amber Blossom City
        120 => (TerrainKind::Hq, Some("ab")), // Amber Blossom HQ
        121 => (TerrainKind::Port, Some("ab")), // Amber Blossom Port
        122 => (TerrainKind::Airport, Some("js")), // Jade Sun Airport
        123 => (TerrainKind::Base, Some("js")), // Jade Sun Base
        124 => (TerrainKind::City, Some("js")), // Jade Sun City
        125 => (TerrainKind::Hq, Some("js")), // Jade Sun HQ
        126 => (TerrainKind::Port, Some("js")), // Jade Sun Port
        127 => (TerrainKind::ComTower, Some("ab")), // Amber Blossom Com Tower
        128 => (TerrainKind::ComTower, Some("bh")), // Black Hole Com Tower
        129 => (TerrainKind::ComTower, Some("bm")), // Blue Moon Com Tower
        130 => (TerrainKind::ComTower, Some("bd")), // Brown Desert Com Tower
        131 => (TerrainKind::ComTower, Some("ge")), // Green Earth Com Tower
        132 => (TerrainKind::ComTower, Some("js")), // Jade Sun Com Tower
        133 => (TerrainKind::ComTower, None), // Neutral Com Tower
        134 => (TerrainKind::ComTower, Some("os")), // Orange Star Com Tower
        135 => (TerrainKind::ComTower, Some("rf")), // Red Fire Com Tower
        136 => (TerrainKind::ComTower, Some("yc")), // Yellow Comet Com Tower
        137 => (TerrainKind::ComTower, Some("gs")), // Grey Sky Com Tower
        138 => (TerrainKind::Lab, Some("ab")), // Amber Blossom Lab
        139 => (TerrainKind::Lab, Some("bh")), // Black Hole Lab
        140 => (TerrainKind::Lab, Some("bm")), // Blue Moon Lab
        141 => (TerrainKind::Lab, Some("bd")), // Brown Desert Lab
        142 => (TerrainKind::Lab, Some("ge")), // Green Earth Lab
        143 => (TerrainKind::Lab, Some("gs")), // Grey Sky Lab
        144 => (TerrainKind::Lab, Some("js")), // Jade Sun Lab
        145 => (TerrainKind::Lab, None), // Neutral Lab
        146 => (TerrainKind::Lab, Some("os")), // Orange Star Lab
        147 => (TerrainKind::Lab, Some("rf")), // Red Fire Lab
        148 => (TerrainKind::Lab, Some("yc")), // Yellow Comet Lab
        149 => (TerrainKind::Airport, Some("ci")), // Cobalt Ice Airport
        150 => (TerrainKind::Base, Some("ci")), // Cobalt Ice Base
        151 => (TerrainKind::City, Some("ci")), // Cobalt Ice City
        152 => (TerrainKind::ComTower, Some("ci")), // Cobalt Ice Com Tower
        153 => (TerrainKind::Hq, Some("ci")), // Cobalt Ice HQ
        154 => (TerrainKind::Lab, Some("ci")), // Cobalt Ice Lab
        155 => (TerrainKind::Port, Some("ci")), // Cobalt Ice Port
        156 => (TerrainKind::Airport, Some("pc")), // Pink Cosmos Airport
        157 => (TerrainKind::Base, Some("pc")), // Pink Cosmos Base
        158 => (TerrainKind::City, Some("pc")), // Pink Cosmos City
        159 => (TerrainKind::ComTower, Some("pc")), // Pink Cosmos Com Tower
        160 => (TerrainKind::Hq, Some("pc")), // Pink Cosmos HQ
        161 => (TerrainKind::Lab, Some("pc")), // Pink Cosmos Lab
        162 => (TerrainKind::Port, Some("pc")), // Pink Cosmos Port
        163 => (TerrainKind::Airport, Some("tg")), // Teal Galaxy Airport
        164 => (TerrainKind::Base, Some("tg")), // Teal Galaxy Base
        165 => (TerrainKind::City, Some("tg")), // Teal Galaxy City
        166 => (TerrainKind::ComTower, Some("tg")), // Teal Galaxy Com Tower
        167 => (TerrainKind::Hq, Some("tg")), // Teal Galaxy HQ
        168 => (TerrainKind::Lab, Some("tg")), // Teal Galaxy Lab
        169 => (TerrainKind::Port, Some("tg")), // Teal Galaxy Port
        170 => (TerrainKind::Airport, Some("pl")), // Purple Lightning Airport
        171 => (TerrainKind::Base, Some("pl")), // Purple Lightning Base
        172 => (TerrainKind::City, Some("pl")), // Purple Lightning City
        173 => (TerrainKind::ComTower, Some("pl")), // Purple Lightning Com Tower
        174 => (TerrainKind::Hq, Some("pl")), // Purple Lightning HQ
        175 => (TerrainKind::Lab, Some("pl")), // Purple Lightning Lab
        176 => (TerrainKind::Port, Some("pl")), // Purple Lightning Port
        181 => (TerrainKind::Airport, Some("ar")), // Acid Rain Airport
        182 => (TerrainKind::Base, Some("ar")), // Acid Rain Base
        183 => (TerrainKind::City, Some("ar")), // Acid Rain City
        184 => (TerrainKind::ComTower, Some("ar")), // Acid Rain Com Tower
        185 => (TerrainKind::Hq, Some("ar")), // Acid Rain HQ
        186 => (TerrainKind::Lab, Some("ar")), // Acid Rain Lab
        187 => (TerrainKind::Port, Some("ar")), // Acid Rain Port
        188 => (TerrainKind::Airport, Some("wn")), // White Nova Airport
        189 => (TerrainKind::Base, Some("wn")), // White Nova Base
        190 => (TerrainKind::City, Some("wn")), // White Nova City
        191 => (TerrainKind::ComTower, Some("wn")), // White Nova Com Tower
        192 => (TerrainKind::Hq, Some("wn")), // White Nova HQ
        193 => (TerrainKind::Lab, Some("wn")), // White Nova Lab
        194 => (TerrainKind::Port, Some("wn")), // White Nova Port
        195 => (TerrainKind::Teleporter, None), // Teleporter
        196 => (TerrainKind::Airport, Some("aa")), // Azure Asteroid Airport
        197 => (TerrainKind::Base, Some("aa")), // Azure Asteroid Base
        198 => (TerrainKind::City, Some("aa")), // Azure Asteroid City
        199 => (TerrainKind::ComTower, Some("aa")), // Azure Asteroid Com Tower
        200 => (TerrainKind::Hq, Some("aa")), // Azure Asteroid HQ
        201 => (TerrainKind::Lab, Some("aa")), // Azure Asteroid Lab
        202 => (TerrainKind::Port, Some("aa")), // Azure Asteroid Port
        203 => (TerrainKind::Airport, Some("ne")), // Noir Eclipse Airport
        204 => (TerrainKind::Base, Some("ne")), // Noir Eclipse Base
        205 => (TerrainKind::City, Some("ne")), // Noir Eclipse City
        206 => (TerrainKind::ComTower, Some("ne")), // Noir Eclipse Com Tower
        207 => (TerrainKind::Hq, Some("ne")), // Noir Eclipse HQ
        208 => (TerrainKind::Lab, Some("ne")), // Noir Eclipse Lab
        209 => (TerrainKind::Port, Some("ne")), // Noir Eclipse Port
        210 => (TerrainKind::Airport, Some("sc")), // Silver Claw Airport
        211 => (TerrainKind::Base, Some("sc")), // Silver Claw Base
        212 => (TerrainKind::City, Some("sc")), // Silver Claw City
        213 => (TerrainKind::ComTower, Some("sc")), // Silver Claw Com Tower
        214 => (TerrainKind::Hq, Some("sc")), // Silver Claw HQ
        215 => (TerrainKind::Lab, Some("sc")), // Silver Claw Lab
        216 => (TerrainKind::Port, Some("sc")), // Silver Claw Port
        217 => (TerrainKind::Airport, Some("uw")), // Umber Wilds Airport
        218 => (TerrainKind::Base, Some("uw")), // Umber Wilds Base
        219 => (TerrainKind::City, Some("uw")), // Umber Wilds City
        220 => (TerrainKind::ComTower, Some("uw")), // Umber Wilds Com Tower
        221 => (TerrainKind::Hq, Some("uw")), // Umber Wilds HQ
        222 => (TerrainKind::Lab, Some("uw")), // Umber Wilds Lab
        223 => (TerrainKind::Port, Some("uw")), // Umber Wilds Port
        _ => return None,
    };
    Some(TerrainIdInfo { kind, country })
}

/// AWBW generic unit id (damage table / Build action) -> UnitType.
pub fn unit_type_by_awbw_id(id: u32) -> Option<UnitType> {
    match id {
        1 => Some(UnitType::Infantry),
        2 => Some(UnitType::Mech),
        3 => Some(UnitType::MdTank),
        4 => Some(UnitType::Tank),
        5 => Some(UnitType::Recon),
        6 => Some(UnitType::Apc),
        7 => Some(UnitType::Artillery),
        8 => Some(UnitType::Rocket),
        9 => Some(UnitType::AntiAir),
        10 => Some(UnitType::Missile),
        11 => Some(UnitType::Fighter),
        12 => Some(UnitType::Bomber),
        13 => Some(UnitType::BCopter),
        14 => Some(UnitType::TCopter),
        15 => Some(UnitType::Battleship),
        16 => Some(UnitType::Cruiser),
        17 => Some(UnitType::Lander),
        18 => Some(UnitType::Sub),
        28 => Some(UnitType::BlackBoat),
        29 => Some(UnitType::Carrier),
        30 => Some(UnitType::Stealth),
        46 => Some(UnitType::Neotank),
        960900 => Some(UnitType::Piperunner),
        968731 => Some(UnitType::BlackBomb),
        1141438 => Some(UnitType::MegaTank),
        _ => None,
    }
}
