"""Generate crates/awbw-engine/src/data.rs from the parsed AWBW data:

  data/units.json          (tools/parse_charts.py <- units.php)
  data/terrain_chart.json  (tools/parse_charts.py <- terrain.php)
  data/terrain_ids.json    (tools/gen_terrain_ids.py <- RizeBot <- AWBW DB dump)
  data/awbw-site/damage_inc.json  (AWBW's own damage table, verbatim)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "crates" / "awbw-engine" / "src" / "data.rs"

# Canonical unit order: ascending AWBW generic id.
UNIT_ORDER = [
    ("Infantry", "Infantry"), ("Mech", "Mech"), ("Md.Tank", "MdTank"),
    ("Tank", "Tank"), ("Recon", "Recon"), ("APC", "Apc"),
    ("Artillery", "Artillery"), ("Rocket", "Rocket"), ("Anti-Air", "AntiAir"),
    ("Missile", "Missile"), ("Fighter", "Fighter"), ("Bomber", "Bomber"),
    ("B-Copter", "BCopter"), ("T-Copter", "TCopter"), ("Battleship", "Battleship"),
    ("Cruiser", "Cruiser"), ("Lander", "Lander"), ("Sub", "Sub"),
    ("Black Boat", "BlackBoat"), ("Carrier", "Carrier"), ("Stealth", "Stealth"),
    ("Neotank", "Neotank"), ("Piperunner", "Piperunner"),
    ("Black Bomb", "BlackBomb"), ("Mega Tank", "MegaTank"),
]

MOVE_TYPES = ["F", "B", "T", "W", "A", "S", "L", "P"]
MOVE_TYPE_NAMES = {
    "F": "Foot", "B": "Boot", "T": "Tread", "W": "Tires",
    "A": "Air", "S": "Sea", "L": "Lander", "P": "Pipe",
}
WEATHERS = ["clear", "rain", "snow"]

# TerrainKind enum order; chart row (gif name) each kind's costs come from.
TERRAIN_KINDS = [
    ("Plain", "plain"), ("Mountain", "mountain"), ("Wood", "wood"),
    ("River", "hriver"), ("Road", "hroad"), ("Bridge", "hbridge"),
    ("Sea", "sea"), ("Shoal", "hshoal"), ("Reef", "reef"),
    ("City", "greenearthcity"), ("Base", "greenearthbase"),
    ("Airport", "greenearthairport"), ("Port", "greenearthport"),
    ("Hq", "greenearthhq"), ("Pipe", "hpipe"),
    ("Silo", "missilesilo"), ("SiloEmpty", "missilesilo"),
    ("ComTower", "greenearthcomtower"), ("Lab", "greenearthlab"),
    ("Teleporter", "teleporter"),
    # Not in the chart: seams and rubble move like pipes (Piperunner only) and
    # grant no terrain stars (special-cased in AWBW's damage calc anyway).
    ("PipeSeam", "hpipe"), ("PipeRubble", "hpipe"),
]
KIND_JSON_TO_RUST = {
    "PLAIN": "Plain", "MOUNTAIN": "Mountain", "WOOD": "Wood", "RIVER": "River",
    "ROAD": "Road", "BRIDGE": "Bridge", "SEA": "Sea", "SHOAL": "Shoal",
    "REEF": "Reef", "CITY": "City", "BASE": "Base", "AIRPORT": "Airport",
    "PORT": "Port", "HQ": "Hq", "PIPE": "Pipe", "SILO": "Silo",
    "SILO_EMPTY": "SiloEmpty", "COM_TOWER": "ComTower", "LAB": "Lab",
    "TELEPORTER": "Teleporter", "PIPE_SEAM": "PipeSeam", "PIPE_RUBBLE": "PipeRubble",
}


def main():
    units = json.loads((DATA / "units.json").read_text())
    chart = {t["gif"]: t for t in json.loads((DATA / "terrain_chart.json").read_text())}
    tids = json.loads((DATA / "terrain_ids.json").read_text())
    dmg = json.loads((DATA / "awbw-site" / "damage_inc.json").read_text())

    n = len(UNIT_ORDER)
    lines = []
    w = lines.append
    w("// AUTO-GENERATED by tools/gen_tables.py -- do not edit by hand.")
    w("// Sources: awbw.amarriner.com units.php / terrain.php / js/damage_inc.json,")
    w("// plus the AWBW terrain-id table via RizeBot's generated terrain-table.ts.")
    w("#![cfg_attr(rustfmt, rustfmt_skip)]")
    w("")
    w("use crate::types::{MoveType, TerrainKind, UnitType};")
    w("")
    w(f"pub const NUM_UNIT_TYPES: usize = {n};")
    w(f"pub const NUM_TERRAIN_KINDS: usize = {len(TERRAIN_KINDS)};")
    w("")
    w("#[derive(Debug, Clone, Copy)]")
    w("pub struct UnitStats {")
    w("    pub name: &'static str,")
    w("    pub awbw_id: u32,")
    w("    pub cost: u32,")
    w("    pub move_points: u8,")
    w("    pub move_type: MoveType,")
    w("    pub max_ammo: u8,")
    w("    pub max_fuel: u8,")
    w("    pub fuel_per_turn: u8,")
    w("    pub fuel_per_turn_hidden: u8,")
    w("    pub vision: u8,")
    w("    pub range_min: u8,")
    w("    pub range_max: u8,")
    w("}")
    w("")
    w(f"/// Indexed by `UnitType as usize`.")
    w(f"pub static UNIT_STATS: [UnitStats; {n}] = [")
    for name, _ in UNIT_ORDER:
        u = units[name]
        w(f'    UnitStats {{ name: "{name}", awbw_id: {u["id"]}, cost: {u["cost"]}, '
          f'move_points: {u["move_points"]}, move_type: MoveType::{MOVE_TYPE_NAMES[u["move_type"]]}, '
          f'max_ammo: {u["max_ammo"]}, max_fuel: {u["max_fuel"]}, '
          f'fuel_per_turn: {u["fuel_per_turn"]}, fuel_per_turn_hidden: {u["fuel_per_turn_hidden"]}, '
          f'vision: {u["vision"]}, range_min: {u["range_min"]}, range_max: {u["range_max"]} }},')
    w("];")
    w("")

    id_to_idx = {units[name]["id"]: i for i, (name, _) in enumerate(UNIT_ORDER)}

    for label, key in (("PRIMARY", "ATTACK1"), ("SECONDARY", "ATTACK2")):
        w(f"/// Base damage % with the {label.lower()} weapon;")
        w("/// -1 = this pairing cannot be attacked with this weapon.")
        w(f"/// Indexed [attacker as usize][defender as usize].")
        w(f"pub static BASE_DAMAGE_{label}: [[i16; {n}]; {n}] = [")
        table = dmg[key]
        for name, _ in UNIT_ORDER:
            aid = str(units[name]["id"])
            row = table.get(aid, {})
            vals = [-1] * n
            for did, v in row.items():
                vals[id_to_idx[int(did)]] = v
            w(f'    [{", ".join(str(v) for v in vals)}], // {name}')
        w("];")
        w("")

    w("/// Movement cost; 0 = impassable.")
    w("/// Indexed [TerrainKind as usize][Weather as usize][MoveType as usize].")
    w(f"pub static MOVE_COST: [[[u8; 8]; 3]; {len(TERRAIN_KINDS)}] = [")
    for kind, gif in TERRAIN_KINDS:
        row = chart[gif]
        per_weather = []
        for weather in WEATHERS:
            costs = row["costs"][weather]
            per_weather.append("[" + ", ".join(
                str(costs[mt] if costs[mt] is not None else 0) for mt in MOVE_TYPES) + "]")
        w(f'    [{", ".join(per_weather)}], // {kind}')
    w("];")
    w("")

    w("/// Terrain defence stars, indexed by `TerrainKind as usize`.")
    w("/// Seams/rubble are stored as 0; AWBW also special-cases them to 0 in combat.")
    defenses = []
    for kind, gif in TERRAIN_KINDS:
        d = 0 if kind in ("PipeSeam", "PipeRubble") else chart[gif]["defense"]
        defenses.append(str(d))
    w(f"pub static TERRAIN_DEFENSE: [u8; {len(TERRAIN_KINDS)}] = [{', '.join(defenses)}];")
    w("")

    w("#[derive(Debug, Clone, Copy)]")
    w("pub struct TerrainIdInfo {")
    w("    pub kind: TerrainKind,")
    w("    /// Owning country code for pre-owned properties; None for neutral/none.")
    w("    pub country: Option<&'static str>,")
    w("}")
    w("")
    w("/// AWBW `terrain_id` (as appearing in maps and replays) -> terrain info.")
    w("pub fn terrain_by_awbw_id(id: u16) -> Option<TerrainIdInfo> {")
    w("    let (kind, country) = match id {")
    for tid in sorted(tids, key=int):
        t = tids[tid]
        kind = KIND_JSON_TO_RUST[t["kind"]]
        country = f'Some("{t["country"]}")' if t["country"] else "None"
        w(f'        {tid} => (TerrainKind::{kind}, {country}), // {t["name"]}')
    w("        _ => return None,")
    w("    };")
    w("    Some(TerrainIdInfo { kind, country })")
    w("}")
    w("")
    w("/// AWBW generic unit id (damage table / Build action) -> UnitType.")
    w("pub fn unit_type_by_awbw_id(id: u32) -> Option<UnitType> {")
    w("    match id {")
    for name, variant in UNIT_ORDER:
        w(f'        {units[name]["id"]} => Some(UnitType::{variant}),')
    w("        _ => None,")
    w("    }")
    w("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
