"""Generate crates/awbw-engine/src/co_data.rs from the AWBW-Replay-Player's
COs.json, which encodes each CO's day-to-day ability in machine-readable form.

Only day-to-day abilities are generated. CO powers change stats mid-turn and the
engine does not model them; the replay harness excludes power-affected turns
from strict checks instead.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(r"F:\awbw\AWBW-Replay-Player\AWBWApp.Resources\Json\COs.json")
OUT = ROOT / "crates" / "awbw-engine" / "src" / "co_data.rs"

# Same order as UnitType in types.rs / gen_tables.py.
UNIT_ORDER = [
    "Infantry", "Mech", "Md.Tank", "Tank", "Recon", "APC", "Artillery", "Rocket",
    "Anti-Air", "Missile", "Fighter", "Bomber", "B-Copter", "T-Copter",
    "Battleship", "Cruiser", "Lander", "Sub", "Black Boat", "Carrier", "Stealth",
    "Neotank", "Piperunner", "Black Bomb", "Mega Tank",
]
INDEX = {name: i for i, name in enumerate(UNIT_ORDER)}
N = len(UNIT_ORDER)

# Abilities COs.json leaves empty but which are well documented; without these,
# two commonly played COs would silently verify as vanilla.
MANUAL = {
    # Lash: +10% attack per terrain star the attacker stands on.
    "Lash": {"condition": "PerTerrainStar", "conditional_attack_all": 10},
    # Adder, Rachel, Javier and Andy have no day-to-day combat effect we model.
    # (Javier's +20% defence against indirects is conditional on the *attacker*
    # being indirect, which the current per-unit table cannot express.)
}


def group_indices(affected):
    if "all" in affected:
        return list(range(N))
    out = []
    for name in affected:
        if name in INDEX:
            out.append(INDEX[name])
    return out


def build(co):
    d2d = co.get("DayToDayPower", {}) or {}
    attack = [0] * N
    defense = [0] * N
    range_delta = [0] * N
    conditional = [0] * N
    condition = "Always"

    for group in d2d.get("PowerIncreases", []):
        idxs = group_indices(group.get("AffectedUnits", []))
        atk = int(round(group.get("PowerIncrease", 0) * 100))
        dfn = int(round(group.get("DefenseIncrease", 0) * 100))
        rng = int(group.get("RangeIncrease", 0))
        terrain = group.get("ConditionalTerrain")
        for i in idxs:
            if terrain:
                conditional[i] += atk
            else:
                attack[i] += atk
            defense[i] += dfn
            range_delta[i] += rng
        if terrain:
            condition = {
                "Building": "UrbanOnly",
                "Road": "RoadOnly",
                "Plain": "PlainOnly",
            }.get(terrain, "Always")

    manual = MANUAL.get(co["Name"])
    if manual:
        condition = manual.get("condition", condition)
        bonus = manual.get("conditional_attack_all")
        if bonus is not None:
            conditional = [bonus] * N

    luck = d2d.get("LuckRange")
    luck_bad, luck_good = 0, 9
    if isinstance(luck, dict):
        # Stored as {"x": worst roll, "y": best roll}; x is negative for COs
        # that can roll badly (Flak, Jugger).
        luck_bad = abs(int(luck.get("x", 0)))
        luck_good = int(luck.get("y", 9))

    return {
        "name": co["Name"],
        "awbw_id": co["AWBWID"],
        "price": int(round(d2d.get("UnitPriceMultiplier", 1.0) * 100)),
        "attack": attack,
        "defense": defense,
        "range": range_delta,
        "conditional": conditional,
        "condition": condition,
        "luck_bad": luck_bad,
        "luck_good": luck_good,
        "fund_bonus": int(d2d.get("PropertyFundIncrease", 0)),
        "air_fuel": int(d2d.get("AirFuelUsageDecrease", 0)),
    }


def arr(values, typ):
    return "[" + ", ".join(str(v) for v in values) + f"]  as [{typ}; {N}]" if False else \
        "[" + ", ".join(str(v) for v in values) + "]"


def main():
    raw = SRC.read_text(encoding="utf-8")
    data = json.loads(re.sub(r"//[^\n]*", "", raw))
    cos = [build(v) for v in data.values()]
    cos.sort(key=lambda c: c["awbw_id"])

    lines = []
    w = lines.append
    w("// AUTO-GENERATED by tools/gen_cos.py -- do not edit by hand.")
    w("// Source: AWBW-Replay-Player's COs.json (day-to-day abilities only).")
    w("#![cfg_attr(rustfmt, rustfmt_skip)]")
    w("")
    w("use crate::data::NUM_UNIT_TYPES;")
    w("")
    w("/// When a CO's conditional attack bonus applies.")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    w("pub enum AttackCondition {")
    w("    /// No conditional bonus.")
    w("    Always,")
    w("    /// Kindle: only while the attacker stands on a property.")
    w("    UrbanOnly,")
    w("    /// Koal: only on roads and bridges.")
    w("    RoadOnly,")
    w("    /// Jake: only on plains.")
    w("    PlainOnly,")
    w("    /// Lash: the bonus is per terrain star under the attacker.")
    w("    PerTerrainStar,")
    w("}")
    w("")
    w("/// A CO's day-to-day ability. Percentages are deltas on the vanilla 100.")
    w("#[derive(Debug, Clone, Copy)]")
    w("pub struct CoData {")
    w("    pub name: &'static str,")
    w("    pub awbw_id: u32,")
    w("    /// Build cost multiplier, as a percentage (100 = normal).")
    w("    pub price_multiplier_pct: u32,")
    w("    /// Attack bonus per unit type, in percentage points.")
    w("    pub attack: [i16; NUM_UNIT_TYPES],")
    w("    pub defense: [i16; NUM_UNIT_TYPES],")
    w("    pub range_delta: [i8; NUM_UNIT_TYPES],")
    w("    /// Extra attack that applies only when `condition` holds.")
    w("    pub conditional_attack: [i16; NUM_UNIT_TYPES],")
    w("    pub condition: AttackCondition,")
    w("    pub luck_bad_max: i32,")
    w("    pub luck_good_max: i32,")
    w("    /// Extra funds per property per day (Sasha).")
    w("    pub property_fund_bonus: u32,")
    w("    /// Fuel per turn air units save (Eagle).")
    w("    pub air_fuel_decrease: u8,")
    w("}")
    w("")
    w("impl CoData {")
    w("    /// A CO with no day-to-day effect at all: the engine's default.")
    w("    pub const VANILLA: CoData = CoData {")
    w('        name: "Andy",')
    w("        awbw_id: 1,")
    w("        price_multiplier_pct: 100,")
    w(f"        attack: [0; NUM_UNIT_TYPES],")
    w(f"        defense: [0; NUM_UNIT_TYPES],")
    w(f"        range_delta: [0; NUM_UNIT_TYPES],")
    w(f"        conditional_attack: [0; NUM_UNIT_TYPES],")
    w("        condition: AttackCondition::Always,")
    w("        luck_bad_max: 0,")
    w("        luck_good_max: 9,")
    w("        property_fund_bonus: 0,")
    w("        air_fuel_decrease: 0,")
    w("    };")
    w("}")
    w("")
    w(f"pub static COS: [CoData; {len(cos)}] = [")
    for c in cos:
        w("    CoData {")
        w(f'        name: "{c["name"]}", awbw_id: {c["awbw_id"]}, '
          f'price_multiplier_pct: {c["price"]},')
        w(f'        attack: {arr(c["attack"], "i16")},')
        w(f'        defense: {arr(c["defense"], "i16")},')
        w(f'        range_delta: {arr(c["range"], "i8")},')
        w(f'        conditional_attack: {arr(c["conditional"], "i16")},')
        w(f'        condition: AttackCondition::{c["condition"]},')
        w(f'        luck_bad_max: {c["luck_bad"]}, luck_good_max: {c["luck_good"]},')
        w(f'        property_fund_bonus: {c["fund_bonus"]}, air_fuel_decrease: {c["air_fuel"]},')
        w("    },")
    w("];")
    w("")
    w("pub fn co_by_awbw_id(id: u32) -> Option<&'static CoData> {")
    w("    COS.iter().find(|c| c.awbw_id == id)")
    w("}")
    w("")
    w("pub fn co_by_name(name: &str) -> Option<&'static CoData> {")
    w("    COS.iter().find(|c| c.name.eq_ignore_ascii_case(name))")
    w("}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(cos)} COs)")
    for c in cos:
        effects = []
        if c["price"] != 100:
            effects.append(f"cost {c['price']}%")
        if any(c["attack"]):
            effects.append(f"atk {min(c['attack'])}..{max(c['attack'])}")
        if any(c["defense"]):
            effects.append(f"def {min(c['defense'])}..{max(c['defense'])}")
        if any(c["conditional"]):
            effects.append(f"cond {c['condition']} +{max(c['conditional'])}")
        if (c["luck_bad"], c["luck_good"]) != (0, 9):
            effects.append(f"luck -{c['luck_bad']}..+{c['luck_good']}")
        if c["fund_bonus"]:
            effects.append(f"funds +{c['fund_bonus']}/property")
        if c["air_fuel"]:
            effects.append(f"air fuel -{c['air_fuel']}")
        if not effects:
            effects.append("none modelled")
        print(f"  {c['name']:12} {', '.join(effects)}")


if __name__ == "__main__":
    main()
